baseURL = "https://kaiseimathclub.github.io"
publishDir = "docs"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
title = '開成学園数学研究部'
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Kaisei Mathematics Club"
  mainSections = ["post","posts"]
  logo = "images/kaiseimathclub.jpg" # Expecting square dimensions
  favicon = "images/kaiseimathclub.jpg"
  dateFormat = "2006年1月2日"
  commit = false
  rss = true
  wordCount = true
  useHLJS = true
  delayDisqus = true
  showRelatedPosts = true
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "開成学園数学研究部"
  website = "yourwebsite.com"
  email = "kaiseimathclub@gmail.com"
  twitter = "Kaisei_Suken"

mainSections = ["post"]

[[menu.main]]
    name = "About"
    url = "page/about"
    weight = 1

[[menu.main]]
	identifier = "fest"
	name = "文化祭"
	weight = 2

[[menu.main]]
	parent = "fest"
	name = "部誌"
	url = "shibuncase/shibuncase_index"
	weight = 1

[[menu.main]]
	parent = "fest"
	name = "GP"
	url = "fest/gp/gp_index"
	weight = 2

[[menu.main]]
	parent = "fest"
	name = "中学入試予想"
	url = "fest/jhs/jhs_index"
	weight = 2

[[menu.main]]
	parent = "fest"
	name = "高校入試予想"
	url = "fest/hs/hs_index"
	weight = 2

[[menu.main]]
	parent = "fest"
	name = "数研部員と勝負！"
	url = "fest/game/game_index"
	weight = 3

[[menu.main]]
	parent = "fest"
	name = "工作展示"
	url = "fest/crafts/crafts"
	weight = 4

[[menu.main]]
    name = "数研合宿"
    url = "camp/camp_index"
    weight = 3